name: sync devopadays-web fork
on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: start sync
      run: gh repo sync devopsdays-london/devopsdays-web
