name: sync devopadays-web fork
on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: start sync
      run: gh repo sync devopsdays-london/devopsdays-web
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
